language: java

jdk: openjdk8

addons:
  firefox: "86.0"

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/org/openmrs

before_install:
    - git clone https://github.com/openmrs/openmrs-contrib-uitestframework.git
    - cd openmrs-contrib-uitestframework
    - mvn clean install
    - cd ../
    - git clone https://github.com/openmrs/openmrs-distro-referenceapplication.git
    - cd openmrs-distro-referenceapplication/ui-tests
    - mvn clean install
    - cd ../../
    - rm -rf openmrs-contrib-uitestframework
    - rm -rf openmrs-distro-referenceapplication

install:
  - echo "cucumber.publish.enabled=true" > src/test/resources/cucumber.properties
  - cp -f src/test/resources/org/openmrs/uitestframework/test-travis-ci.properties src/test/resources/org/openmrs/uitestframework/test.properties