name: Cucumber Ref App
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  repository_dispatch:
    types: [qa]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      firefox:
        image: selenium/node-firefox:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout ui test framework
        uses: actions/checkout@master
        with:
          repository: openmrs/openmrs-contrib-uitestframework
      - name: Build ui test framework
        run: mvn clean install -B
      - name: Checkout distro/uitests
        uses: actions/checkout@master
        with:
          repository: openmrs/openmrs-distro-referenceapplication
      - name: Build distro/uitests
        run: mvn clean install -B
      - name: Checkout qaframework
        uses: actions/checkout@master
        with:
          repository: openmrs/openmrs-contrib-qaframework
      - name: Run qaframework on selenium
        run: |
          echo "cucumber.publish.enabled=true" > src/test/resources/cucumber.properties
          cp -f src/test/resources/org/openmrs/uitestframework/test-ci.properties src/test/resources/org/openmrs/uitestframework/test.properties
          mvn clean install -DskipTests=true
          npm run refappSelenium